#0
! **********************************
! Generated by: AJP Path Builder v0.1
! Axes: XYZTR=XY---
! Resolution: 1,1,-,-,-
! some file path
! **********************************

! Alignment Structure:
If (gIntFindFids = 1)
     gDblFidX(1) = 0
     gDblFidY(1) = 0
     gDblFidX(2) = 0
     gDblFidY(2) = 0
     Stop
End

Loop 1
ptp/ev XY,0.8660,1.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,0.8660,1.0000
line XY,1.7321,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.5981,1.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,2.5981,1.0000
line XY,1.7321,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,1.7321,2.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,1.7321,2.5000
line XY,1.7321,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,1.7321,1.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.5981,1.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,2.5981,1.0000
line XY,3.4641,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.3301,1.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,4.3301,1.0000
line XY,3.4641,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.4641,2.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,3.4641,2.5000
line XY,3.4641,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.4641,1.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.3301,1.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,4.3301,1.0000
line XY,5.1962,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,6.0622,1.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,6.0622,1.0000
line XY,5.1962,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,5.1962,2.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,5.1962,2.5000
line XY,5.1962,1.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,5.1962,1.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,1.8660,2.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,1.8660,2.5000
line XY,2.7321,3.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.5981,2.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,3.5981,2.5000
line XY,2.7321,3.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.7321,4.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,2.7321,4.0000
line XY,2.7321,3.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.7321,3.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.5981,2.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,3.5981,2.5000
line XY,4.4641,3.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,5.3301,2.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,5.3301,2.5000
line XY,4.4641,3.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.4641,4.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,4.4641,4.0000
line XY,4.4641,3.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.4641,3.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.8660,4.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,2.8660,4.0000
line XY,3.7321,4.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.5981,4.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,4.5981,4.0000
line XY,3.7321,4.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.7321,5.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,3.7321,5.5000
line XY,3.7321,4.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.7321,4.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,1.7321,1.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,1.7321,1.5000
line XY,2.5981,2.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.4641,1.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,3.4641,1.5000
line XY,2.5981,2.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.5981,3.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,2.5981,3.0000
line XY,2.5981,2.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.5981,2.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.4641,1.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,3.4641,1.5000
line XY,4.3301,2.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,5.1962,1.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,5.1962,1.5000
line XY,4.3301,2.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.3301,3.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,4.3301,3.0000
line XY,4.3301,2.0000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.3301,2.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,2.7321,3.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,2.7321,3.0000
line XY,3.5981,3.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,4.4641,3.0000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,4.4641,3.0000
line XY,3.5981,3.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.5981,4.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 5
MSEG XY,3.5981,4.5000
line XY,3.5981,3.5000
ENDS XY
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0

ptp/ev XY,3.5981,3.5000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 100
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0


END
STOP
